# This script is a modified version of the one provided by github.com/bool64/dev.
name: benchmark
on:
  pull_request:
  workflow_dispatch:
    inputs:
      old:
        description: 'Old Ref'
        required: false
        default: 'main'
      new:
        description: 'New Ref'
        required: true

# Cancel the workflow in progress in newer build is about to start.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  GO111MODULE: "on"
  RUN_BASE_BENCHMARK: "on"
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ (github.event.inputs.new != '') && github.event.inputs.new || github.event.ref }}

      - name: Install Go stable
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Go cache
        uses: actions/cache@v3
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-cache

      - name: Cache mage
        id: cache-mage
        uses: actions/cache@v3
        with:
          path: ~/go/bin/mage
          key: ${{ runner.os }}-mage

      - name: Download mage
        if: steps.cache-mage.outputs.cache-hit != 'true'
        run: go install github.com/magefile/mage@v1.13.0

      - name: Restore benchstat
        uses: actions/cache@v3
        with:
          path: ~/go/bin/benchstat
          key: ${{ runner.os }}-benchstat-legacy

      - name: Benchmark results for changes
        id: bench-next
        run: |
          OUTPUT=$(mage benchmark:run bench-next)
          echo "${OUTPUT}"
          echo "next<<EOF" >> $GITHUB_OUTPUT && cat bench-next >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT

      - name: Benchmark results for base
        id: bench-base
        if: env.RUN_BASE_BENCHMARK == 'on' && (github.event.pull_request.base.sha != '' || github.event.inputs.old != '')
        run: |
          git fetch origin main ${{ github.event.pull_request.base.sha }}
          HEAD=$(git rev-parse HEAD)
          git reset --hard ${{ github.event.pull_request.base.sha }}
          BASE=$(mage benchmark:run bench-main)
          git reset --hard $HEAD
          echo "base<<EOF" >> $GITHUB_OUTPUT && cat bench-main >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT

      - name: Benchmark diff against base
        id: bench-diff
        run: |
          echo "${{ steps.bench-next.outputs.next }}" > bench-next
          echo "${{ steps.bench-base.outputs.base }}" > bench-base
          OUTPUT=$(mage benchmark:diff bench-base bench-next bench-diff)
          echo "${OUTPUT}"
          echo "diff<<EOF" >> $GITHUB_OUTPUT && cat bench-diff >> $GITHUB_OUTPUT && echo "EOF" >> $GITHUB_OUTPUT

      - name: Write benchmark summary
        uses: WcAServices/markdown-template-action@v1.0.2
        with:
          variables: >-
            DIFF_OUT="${{ steps.bench-diff.outputs.diff }}"
            NEXT_OUT="${{ steps.bench-next.outputs.next }}"

          template: |
            ### Benchmark Summary :rocket:
            <details><summary>Benchmark diff with base branch</summary>
            
            ```bash
            $DIFF_OUT
            ```
            </details>
            
            <details><summary>Benchmark result</summary>
            
            ```bash
            $NEXT_OUT
            ```
            </details>  

      - name: Comment benchmark result
        continue-on-error: true
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: benchmark
          message: |
            ### Benchmark Result
            <details><summary>Benchmark diff against base branch</summary>

            ```bash
            ${{ steps.bench-diff.outputs.diff }}
            ```
            </details>

            <details><summary>Benchmark result</summary>

            ```bash
            ${{ steps.bench-next.outputs.next }}
            ```
            </details>
